summary screen + activity screen
tusxxx/Step-Master pull request #4
Opened 2023-11-22 15:32 UTC by a-vengrzhinovskaya

2023-11-22 17:47 UTC, tusxxx requested changes

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/SummaryScreen.kt
> +    onChangeBodyComposition: (Float?, Float?, Float?, Float?) -> Unit,
а чё за флоуты

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/activity/ActivityBlock.kt
> +                .weight(0.3f)
.он нужен?

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/steps/StepsBlock.kt
> +                LinearProgressIndicator(
strokeCap квадратный

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/steps/StepsGoalEditDialog.kt
> +fun StepsGoalEditDialog(
.нету shadow

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/water/WaterBlock.kt
> +        Column(modifier = Modifier.weight(0.7f)) {
веса убери

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/water/WaterIconButton.kt
> +package com.tusxapps.step_master.android.ui.components
посмотри ворнинги

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionBlock.kt
> +    val isDialogOpen = remember { mutableStateOf(false) }
.делегаты мб

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionBlock.kt
> +                        (fatValue / weightValue * 1000).roundToInt() / 10.toFloat()
убери куда-нибудь

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyInfoItem.kt
> +                text = value.toString().takeIf { value != null } ?: "__",
-- мб

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionEditDialog.kt
> +                    modifier = Modifier.weight(0.5f),
1

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionEditDialog.kt
> +                    heightValue.value.toFloatOrNull()?.let { height ->
clown

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionEditDialog.kt
> +    onSaveButtonClick: (Float?, Float?, Float?, Float?) -> Unit
names

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/activity/ActivityScreen.kt
> +        verticalArrangement = Arrangement.Top,
.это нужно?

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/components/PrimaryTopBar.kt
> +fun PrimaryTopBar(
позорище 
```kotlin
 Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        IconButton(onClick = onBackClick) {
            Icon(
                modifier = Modifier.size(34.dp),
                painter = painterResource(id = R.drawable.ic_arrow_left),
                contentDescription = null
            )
        }
        Text(text = text, style = MaterialTheme.typography.headlineLarge)
        Spacer(modifier = Modifier.weight(1f))
        icon?.let {
            IconButton(onClick = onIconClick) {
                Icon(
                    painter = painterResource(id = icon),
                    contentDescription = null
                )
            }
        }
    }
    
    ```

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/activity/components/activity/ActivityBlock.kt
> +                    (steps.toFloat() / STEPS_IN_KILOMETER * 10).roundToInt() / 10.toFloat()
выкинь

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/activity/components/activity/ActivityBlock.kt
> +                    (steps.toFloat() / STEPS_IN_KILOMETER * 10).roundToInt() / 10.toFloat()
toAverageKm()

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/activity/components/activity/ActivityInfoIcon.kt
> +fun ActivityInfoIcon(
rename

2023-11-22 17:47 UTC, tusxxx commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/EditDialogTextField.kt
> +fun EditDialogTextField(
DialogTextField

2023-11-22 17:47 UTC, tusxxx commented on shared/src/commonMain/kotlin/com/tusxapps/step_master/domain/calendar/WeekDay.kt
> +    SUNDAY("Вс"),
.русский не нужон тут

2023-11-27 12:18 UTC, a-vengrzhinovskaya commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionEditDialog.kt
> +                    modifier = Modifier.weight(0.5f),
ne poluchaetsya

2023-11-27 12:19 UTC, a-vengrzhinovskaya commented on androidApp/src/main/java/com/tusxapps/step_master/android/ui/main/summary/components/body/BodyCompositionEditDialog.kt
> +                    modifier = Modifier.weight(0.5f),
> 1

ne poluchaetsya

2023-11-28 03:35 UTC, tusxxx approved these changes

2023-11-28 03:35 UTC, merged